### ISSUE TITLE
Improve balance updates

### ISSUE THREAD

**Issue by paOol** [badger-cash/badger-mobile#109]
a side effect of polling to refresh balances sometimes empties the token vault,
or sometimes shows the BCH balance as 0.

instead of updating the view on every poll, it should only update when there is a difference so the user is not left wondering where their balance went.

**Comment by SpicyPete** [comment]
@paOol 
This will be an interesting one to solve, as right now every time it polls it re-calculates the full amount from the UTXO.  When it goes to 0, that means the SLP, or the BCH UTXO endpoints are failing to return the correct data.  So it is only updating the view right now when there is a difference.  

Curious how you propose to solve this, since funds can be sent from different versions of the wallet (extension), or a different wallet entirely, so when the UTXO's get pulled, it makes sense to re-calculate the full balance.
